def COLOR_MAP = [
  'SUCCESS': 'good',
  'FAILURE': 'danger',
]


pipeline {

    agent any
    
    tools{
      maven "MAVEN3"
      jdk "OracleJDK8"
    }
      
        environment {
        NEXUS_USER = 'admin'
        NEXUS_PASS = 'Gabbar$8'
        NEXUSIP = '172.200.227.229'
        NEXUSPORT = '8081'
        RELEASE_REPO ='vprofile-release'
        NEXUS_GRP_REPO ='vpro-maven-group'
        NEXUS_LOGIN= 'nexuslogin'
        CENTRAL_REPO = 'vpro-maven-central'
        SONARSERVER = 'sonarserver'
        SONARSCANNER ='sonarscanner'
        NEXUS_VERSION = 'nexus3'
        NEXUS_PROTOCOL = 'http'
        NEXUS_URL = '172.200.227.229:8081'
        NEXUS_REPOSITORY = 'vprofile-release'


    //  AZURE_CREDENTIALS = credentials('azure-service-principal')
        AZURE_CREDENTIALS = 'azure-sp'
        ACR_SERVER = 'jenkinsacr2024.azurecr.io'
        IMAGE_NAME = 'artifactsimage'

    }
   stages{
      stage('BUILD'){
        steps {
            sh 'mvn -s settings.xml -DskipTests install'
         }
         post{
          success {
            echo "Now Archiving"
            archiveArtifacts artifacts: '**/*.war'
          }
         }
      }
        stage('TEST'){
        steps {
            sh 'mvn test'
         }
       }
        stage('CheckStyle Analysis'){
        steps {
            sh 'mvn checkstyle:checkstyle'
         }

        }
        stage('CODE ANALYSIS with SONARQUBE') {
          
		         environment {
             scannerHome = tool "${SONARSCANNER}"
          }

          steps {
            withSonarQubeEnv("${SONARSERVER}") {
               sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                   -Dsonar.projectName=vprofile-repo \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''

               }    
          } 
        }  
       
       stage("Quality Gates"){
        steps{
          timeout(time: 1, unit: 'HOURS'){
          waitForQualityGate abortPipeline: true
          }
        }
       }

       stage('ArtifactsUpload Nexus'){
        steps{
        nexusArtifactUploader(
        nexusVersion: 'nexus3',
        protocol: 'http',
        nexusUrl: '172.200.227.229:8081',
        groupId: 'QA',
        version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
        repository: 'vprofile-release',
        credentialsId: "${NEXUS_LOGIN}",
        artifacts: [
            [artifactId: 'vprofile',
             classifier: '',
             file: 'target/vprofile-v2.war',
             type: 'war']
        ] )

        }
       }



        stage('Build Docker Image') {
            steps {
                script {
                  docker.build("${ACR_SERVER}/${IMAGE_NAME}:${env.BUILD_NUMBER}")
                }
            }
        }

        stage('Login to Azure') {
            steps {
                script {
                    def azLogin = "az login --service-principal -u ${AZURE_CREDENTIALS.clientId} -p ${AZURE_CREDENTIALS.clientSecret} --tenant ${AZURE_CREDENTIALS.tenantId}"
                    sh(azLogin)
                }
            }
        }

        stage('Push Image to ACR') {
            steps {
                script {
                    docker.withRegistry("${ACR_SERVER}", "${AZURE_CREDENTIALS}") {
                        docker.image("${ACR_SERVER}/${IMAGE_NAME}:${env.BUILD_NUMBER}").push()
                    }
                }
            }
        }
    
  
     post { 
       always {
           echo 'Slack Notification.'
                  slackSend channel: '#intigration_with_jenkins',
                  color: COLOR_MAP[currentBuild.currentResult],
                  message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n more information at: ${env.BUILD_URL}"
         }
      }

  }
}

